name: medigo_doctor
description: A new Flutter project for the MediGo Doctor Portal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #url_launcher: ^6.3.0 # <-- ADD THIS LINE
  flutter_localizations: # Needed for translations
    sdk: flutter
  
  # === ALL REQUIRED PACKAGES ===
  supabase_flutter: ^2.5.8
  google_fonts: ^6.2.1
  intl: ^0.20.2 
  flutter_animate: ^4.5.0 # For animations
  provider: ^6.1.2 # For state management
  url_launcher: ^6.3.0 # For making calls
  table_calendar: ^3.1.2 # The calendar package
  # For the horizontal scroller
  
  # --- NEW PACKAGES FOR FILE UPLOADS ---
  file_picker: ^8.0.6
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  # ===================================
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # <-- ADD THIS LINE
  flutter_native_splash: ^2.4.0  # <-- ADD THIS LINE
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true # This must be true
# ... (rest of your file)

# ADD THESE LINES AT THE VERY BOTTOM
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
# ... (rest of your file)

# ADD THIS NEW SECTION AT THE BOTTOM
flutter_native_splash:
  color: "#FFFFFF"  # <-- This is the white background color
  image: assets/images/logo.png # <-- This is your logo
  android: true
  ios: true